- name: Install Nginx
  package: name=nginx state=present

- name: Start Nginx
  service: name=nginx state=started
    
- name: Creating first website directory - {{ first_website_name }}
  file:
          path: /var/www/{{ first_website_name }}.com
          state: directory

- name: Creating second website directory - {{ second_website_name }}
  file:
          path: /var/www/{{ second_website_name }}.com
          state: directory 

- name: Fetching code for first website
  unarchive:
      src: " {{ codelocation_one }}"
      dest: /home/ec2-user
      remote_src: yes

- name: Placing files on the shelf for webiste - one
  copy:
      src: /home/ec2-user/{{ first_website_name }}/
      dest: /var/www/{{ first_website_name}}.com
      remote_src: yes
  tags: shop

- name: Fetching code for second website
  unarchive:
      src: " {{ codelocation_two }}"
      dest: /home/ec2-user
      remote_src: yes

- name: Placing files on the shelf for webiste - two
  copy:
      src: /home/ec2-user/{{ second_website_name }}/
      dest: /var/www/{{ second_website_name }}.com
      remote_src: yes
  tags: travel

- name: Creating directories for certificates
  file:
          path: /etc/nginx/certs
          state: directory

- name: Creating global private key for websites
  command: "openssl genrsa -out /etc/nginx/certs/sites.key 2048"

- name: Creating global certificate file for websites
  command: "openssl req -key /etc/nginx/certs/sites.key -new -x509 -days 365 -subj '/CN=*.sites.com/O=ITS Pvt Ltd/C=IN' -out /etc/nginx/certs/sites.crt"

- name: Creating virtualhost configurations for websites and moving to respective location
  template:
        src: files/sites.j2
        dest: /etc/nginx/conf.d/sites.com.conf

- name: Setting sebool for Redhat system
  command: semanage permissive -a httpd_t

- name: Restarting Web Services for changes to take place
  command: echo "Final Destination Reached"
  notify:
          - Restart nginx
