  - name: Removing {{first_website_name}} from var directory
    ansible.builtin.file:
            path: /var/www/{{website1}}
            state: absent

  - name: Removing {{second_website_name}} from var directory
    ansible.builtin.file:
            path: /var/www/{{website2}}
            state: absent

  - name: Removing Virtual hosts configurations from {{first_website_name}}
    ansible.builtin.file:
            path: "{{ item }}"
            state: absent 
    loop:
            - /etc/nginx/sites-available/sites.com.conf
            - /etc/nginx/sites-enabled/sites.com.conf
    when: ansible_os_family == "Debian"

  - name: Removing Virtual hosts configurations
    ansible.builtin.file:
            path: /etc/nginx/conf.d/sites.com.conf
            state: absent
    when: ansible_os_family == "RedHat"

  - name: Restarting Apache on Ubuntu
    service:
        name: nginx
        state: restarted
